const mongoose=require('mongoose');
const orderSchema=new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        country:{
            type:String,
            default:"US"
        },
        city:{
            type:String,
            required:true
        },
        phone:{
            type:String,
            required:true
        },
        pincode:{
            type:String,
            required:true
        }
    },
    user:{
        type:mongoose.SchemaTypes.ObjectId,
        required:true,
        ref:"User"
    },
    orderItems:[{
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        product:{
            type:mongoose.SchemaTypes.ObjectId,
            required:true,
            ref:"Product"
        }
    }],
    itemsPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    Shipping:{
        type:Number,
        required:true,
        default:0.0
    },
    totalPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    paymentInfo:{
      id:{
        type:String,
        require:true
      },
      status:{
        type:String,
        required:true
      }
    },
    paidAt:{
        type:Date,
        default:Date.now
    }, 
    DeliveryAt:{
        type:Date,
    },
    orderStatus:{
        type:String,
        required:true,
        default:"proceesing"
    },
    createdAt:{
        type:Date,
        default:Date.now
    }
})

let order_model=mongoose.model('Order',orderSchema);
module.exports=order_model;